linkWorkspacePackages: true
packages:
    - "packages/*"

blockExoticSubdeps: true
minimumReleaseAge: 10080 # 7 days in minutes
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200 # 30 days in minutes
