name: Build

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
            - name: Install pnpm
              uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413
            - name: Use Node.js 24
              uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
              with:
                  node-version: "24"
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm run build
            - name: Lint
              run: pnpm run lint
            - name: Test
              run: pnpm run test
